version: "3.8"

services:
  simple_app:
    build: .
    container_name: simple_app
    ports:
      - "3000:3000" # Expose port 3000
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development

  mariadb:
    image: mariadb
    container_name: simple_app_mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    image: nginx
    container_name: simple_app_nginx
    ports:
      - "444:443"
      - "4081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - simple_app

networks:
  simple_app_network:

volumes:
  mariadb_data:
